version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod              # <─ picks up your Dockerfile's prod stage
    image: java-backend:prod    # tag the prod image
    container_name: java-backend-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: prod              # <─ picks up your Dockerfile's prod stage
    image: angular-frontend:prod
    container_name: angular-frontend-prod
    ports:
      - "80:80"                 # assuming your prod stage serves on 80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge