services:
  backend:
    build:
      context: ../backend
      target: dev
    container_name: java-backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      target: dev
    image: angular-frontend:dev
    container_name: angular-frontend-dev
    volumes:
      - ../frontend/src/:/app/src/
    ports:
      - "4200:4200"
    command: npm run start
    networks:
      - app-network
#    depends_on:
#      - backend

networks:
  app-network:
    driver: bridge